language: c

compiler:
  - gcc

arch:
  - amd64
  - arm64
  - ppc64le
  - s390x

os:
  - linux
dist: bionic

addons:
  apt:
    update: true
    packages:
      - linux-headers-$(uname -r)

script:
    - uname -a
    - echo TRAVIS_ARCH = $TRAVIS_ARCH
    - apt-cache search "linux-headers-*"
